const SONGS_ANIME = {
    name:"🫧アニソン🫧",
    categories:[
      {name:"マクロス",items:[
        {name:"マクロスF",songs:[
          "星間飛行",
          "虹いろ・クマクマ",
          "アイモ",
          "射手座午後九時☆Don’t be late",
          "トライアングラー",
          "ノーザンクロス"
        ]},
        {name:"マクロスΔ",songs:[
          "ルンがピカッと光ったら",
          "破滅の純情",
          "いけないボーダーライン",
          "1度だけの恋なら",
          "不確定性☆COZMIC MOVEMENT",
          "絶対零度θノヴァティック",
          "未来はオンナのためにある",
          "ルンに花咲く恋もある"
        ]}
      ]},
      {name:"推しの子",items:[
        {name:"OP・ED",songs:[
          "アイドル"
        ]},
        {name:"B小町",songs:[
          "サインはB",
          "STAR☆T☆RAIN",
          "HEART's♡KISS",
          "Bのリベンジ",
          "POP IN 2",
          "Say What?",
          "深海52Hz",
          "我ら完全無敵のアイドル"
        ]}
      ]},
      {name:"けいおん!!",items:[
        {name:"けいおん!!",songs:[
          "ふわふわ時間",
          "GO!GO!MANIAC",
          "Cagayake!GIRLS"
        ]}
      ]},
      {name:"ブレンド・S",items:[
        {name:"ブレンド・S",songs:[
          "ぼなぺてぃーと♡S",
          "マフユ・フリル・イズム",
          "明日も世界の真ん中で♡",
          "ポジティブレボリューション",
          "妄想ワーキングタイム"
        ]}
      ]},
      {name:"ひなこのーと",items:[
        {name:"ひなこのーと",songs:[
          "あ・え・い・う・え・お・あお!!",
          "かーてんこーる!!!!!",
          "ドラマチックデイズ",
          "爛漫ロード",
          "Sweet A La Mode"
        ]}
      ]},
      {name:"カッコウの許嫁",items:[
        {name:"カッコウの許嫁",songs:[
          "漏電"
        ]}
      ]},
      {name:"神のみぞ知るセカイ",items:[
        {name:"神のみぞ知るセカイ",songs:[
          "ハッピークレセント",
          "NAKED GENIUS"
        ]}
      ]},
      {name:"ごちうさ",items:[
        {name:"ごちうさ",songs:[
          "Daydream café"
        ]}
      ]},
      {name:"かのかり",items:[
        {name:"かのかり",songs:[
          "彼女宣言",
          "DATE",
          "まみらっぷ",
          "桜Selfish"
        ]}
      ]},
      {name:"小林さんちのメイドラゴン",items:[
        {name:"小林さんちのメイドラゴン",songs:[
          "愛のシュプリーム!",
          "イシュカン‪‪♥︎⁡リレーションシップ",
          "青空のラプソディ"
        ]}
      ]},
      {name:"阿波連さんははかれない",items:[
        {name:"阿波連さんははかれない",songs:[
          "AHAREN HEART",
          "はなれない距離"
        ]}
      ]}
    ]
};