const SONGS_VOCALOID = {
  name: "🫧ボカロ🫧",
  categories: [
    {name:"電ポルP",directSongs:true,items:[{name:"電ポルP",songs:["スキスキ絶頂症","Lap Tap Love","さよならテンダー","唯々なりレイデエ","愛に奇術師","独りんぼエンヴィー","従属ふりったー","magic city","ノンデ・パナシーア","心象カスケード","常世の気まぐれ","はらぺこのルベル","曖昧劣情lover"]}]},
    {name:"とあ",directSongs:true,items:[{name:"とあ",songs:["ツギハギスタッカート","ミュージックミュージック","パズルガール","さよならスーヴェニア","ピチカートドロップス","ドライドライフラワー","アイディスマイル"]}]},
    {name:"すこっぷ",directSongs:true,items:[{name:"すこっぷ",songs:["指切り","ラジカル男女の唄"]}]},
    {name:"つなまる",directSongs:true,items:[{name:"つなまる",songs:["月乃","paranoia","うそつき","言の葉クリニック","ひよたまカフェ"]}]},
    {name:"あ子",directSongs:true,items:[{name:"あ子",songs:["milk","渦中にて","グリーディー・ガール","ちゃんちゃら"]}]},
    {name:"香椎モイミ",directSongs:true,items:[{name:"香椎モイミ",songs:["偏食","しょってぃん","キャットラビング","アタシ：アップデート","初恋日記","ラブリーアサシン","ピカピカキャンディラブイズム","Makeup","バッドエンドメーカー"]}]},
    {name:"MARETU",directSongs:true,items:[{name:"MARETU",songs:["脳内革命ガール","マインドブランド","うみたがり","ホワイトハッピー","ダーリン","ぴんく","あいしていたのに","エンゼル92","ビノミ","イヤイヤヨ"]}]},
    {name:"cat nap",directSongs:true,items:[{name:"cat nap",songs:["ペシュテ","ミッドナイト・プール","slow snow dance","キスしてやりたい","latencyはまってくれない","wolf","まほろばポルカ","お邪魔します天国","レイジー・クルーズ","こめっと","サイゼのない町","エジソン","yawn","温度","みはるかす"]}]},
    {name:"ヤマギシコージ",directSongs:true,items:[{name:"ヤマギシコージ",songs:["ロンリー・ポップ・プリンセス","アルコ・ホリック・シンデレラ","シークレット・シーカー","ハイド・アンド・シーフ"]}]},
    {name:"小宮かふぃー",directSongs:true,items:[{name:"小宮かふぃー",songs:["ハロー、メランコリィ","クランベリーパレード","スモーキィクォーツ","ふわふわトラベラーズ"]}]},
    {name:"はるまきごはん",directSongs:true,items:[{name:"はるまきごはん",songs:["メルティランドナイトメア","第三の心臓 −2?","ディナーベル −4","ゼロトーキング","エンパープル"]}]},
    {name:"ピノキオピー",directSongs:true,items:[{name:"ピノキオピー",songs:["腐れ外道とチョコレゐト","ありふれたせかいせいふく","こどものしくみ","アップルドットコム","セカイはまだ始まってすらいない","ねぇねぇねぇ。","神っぽいな","魔法少女とチョコレゐト","デビルじゃないもん","甘噛みでおねがい","アポカリプスなう","Aじゃないか","嘘ミーム","愛属性 −3"]}]},
    {name:"DECO*27",directSongs:true,items:[{name:"DECO*27",songs:["ゆめゆめ","妄想税","おじゃま虫","ストリーミングハート","ハートアラモード","ゴーストルール","ライアーダンス","いいや","妄想感傷代償連盟","ヒバナ","愛言葉III","乙女解剖","スクランブル交際","サイコグラム","ポジティブ・パレード","アンデッドアリス","ヴァンパイア","シンデレラ","シンデレラ(Giga First Night Remix )","サラマンダー","ゾンビ","毒林檎","ラビットホール","ルーキー","ハオ","ネバーランド","モニタリング","モニタリング(Best Friend Remix)","テレパシ","チェリーポップ","ラブパラ"]}]},
    {name:"ミルグラム(DECO*27)",directSongs:true,items:[{name:"ミルグラム(DECO*27)",songs:["おまじない","愛なんですよ","アフターペイン","アンビリカル","事変上等","粛清マーチ","Cat","だいすき","悪くないもん","Tear Drop","バックドラフト","ペイン","なんでもにうむ"]}]},
    {name:"Giga",directSongs:true,items:[{name:"Giga",songs:["ぴんこすてぃっくluv","LUVORATORRRRRY!","drop pop candy","ヒビカセ","Gimme×Gimme","ワーワーワールド","GETCHA!(1番まで)","Ready_Steady","CH4NGE","Beyond the Way","ULTRA C","プレイ","[A]ddiction"]}]},
    {name:"八王子P",directSongs:true,items:[{name:"八王子P",songs:["気まぐれメルシィ","バイオレンストリガー"]}]},
    {name:"かいりきベア",directSongs:true,items:[{name:"かいりきベア",songs:["失敗作少女","アルカリレットウセイ","レミングミング","アンヘル","マオ","ベノム","ルマ","アイ情劣等生","ダーリンダンス","メンタルチェンソー","バグ","メロメロイド"]}]},
    {name:"きくお",directSongs:true,items:[{name:"きくお",songs:["愛して愛して愛して","うらみのワルツ","猫の食卓","あなぐらぐらし","イイコと妖狐","見つかんない見つかんない","幸福な死を","君はできない子"]}]},
    {name:"Junky",directSongs:true,items:[{name:"Junky",songs:["メランコリック","Happy Halloween","スイートマジック","オシオキGIMMICK!!"]}]},
    {name:"40mp",directSongs:true,items:[{name:"40mp",songs:["妄想スケッチ","からくりピエロ","ドレミファロンド","恋愛裁判","雨音ノイズ","だんだん早くなる","恋愛マニュアル","大正ロマンチック","ひとりぼっちのひとりごと","悪役にキスシーンを","嘘つきは恋のはじまり"]}]},
    {name:"OSTER project",directSongs:true,items:[{name:"OSTER project",songs:["Alice in Musicland","おおかみなんかこわくないッ！","on the rocks","ナポナポリターンマッチ","トキシックジャム","くじらライダー","いるかジェット","ミラクルペイント","恋色病棟","恋色監獄","おひめさまになりたいのッ！","EAT ME","ゴシップ","軋んだ夢と糸繰人形","アルコールソング","恋の才能","世界を照らすテトラッド","せんぱい！"]}]},
    {name:"いよわ",directSongs:true,items:[{name:"いよわ",songs:["IMWANOKIWA","くろうばあないと","1000年生きてる","あだぽしゃ","きゅうくらりん","アプリコット","パジャミィ","異星にいこうね","ももいろの鍵","ゆめみるうろこ","散歩の邪魔"]}]},
    {name:"r-906",directSongs:true,items:[{name:"r-906",songs:["パノプティコン","あなたしか見えないの","三日月ステップ"]}]},
    {name:"LonePi",directSongs:true,items:[{name:"LonePi",songs:["水死体は恋したい","ゲンチアナ","幸福刑"]}]},
    {name:"TOKOTOKO(西沢さんP)",directSongs:true,items:[{name:"TOKOTOKO(西沢さんP)",songs:["路地裏猫の正体","夜もすがら君想ふ","君色に染まる","僕らの街に愛が降る夜だ","インナーダーク","君の彼女","Booo!","ランウェイのファンタジスタ","チーズケーキクライシス","マイルームコレクション","Sheepret!","ワールドワイドワンダー","水曜日に御用心","はいしんどろーむ"]}]},
    {name:"一二三",directSongs:true,items:[{name:"一二三",songs:["美しく、闇","欲浴","萌す心を"]}]},
    {name:"てにをは",directSongs:true,items:[{name:"てにをは",songs:["ザムザ","お行儀よくね","デビル","ヴィラン"]}]},
    {name:"なきそ",directSongs:true,items:[{name:"なきそ",songs:["毒して頂戴","触れたら最後","ド屑","甘ったる","みまま","お呪い","絶交","みなごろし","ひみつ気分","今すぐ輪廻"]}]},
    {name:"内緒のピアス",directSongs:true,items:[{name:"内緒のピアス",songs:["隣の席のアルキメデス −3","プロポーズ"]}]},
    {name:"稲葉曇",directSongs:true,items:[{name:"稲葉曇",songs:["ラグトレイン","レイニーブーツ","私は雨"]}]},
    {name:"DATEKEN",directSongs:true,items:[{name:"DATEKEN",songs:["蜜月アン・ドゥ・トロワ","ワンルーム・オール・ザット・ジャズ"]}]},
    {name:"パトリチェフ音楽工房",directSongs:true,items:[{name:"パトリチェフ音楽工房",songs:["エンゼルフィッシュ","サンセンチメーター"]}]},
    {name:"キノシタ",directSongs:true,items:[{name:"キノシタ",songs:["はやくそれになりたい！","ポジティブ☆ダンスタイム","ハナイロ☆シャイガール","ガチコイワズライ","ポッピンキャンディ☆フィーバー！","エライエライエライ","夢色フェスティバル"]}]},
    {name:"きさら",directSongs:true,items:[{name:"きさら",songs:["LIMITED QUEEN","スターダストメドレー"]}]},
    {name:"じん",directSongs:true,items:[{name:"じん",songs:["空想フォレスト","如月アテンション","オツキミリサイタル","夕景イエスタデイ","daze"]}]},
    {name:"煮ル果実",directSongs:true,items:[{name:"煮ル果実",songs:["ハングリーニコル","紗痲","キルマー","アイロニーナ","トリコロージュ","トラフィック・ジャム +5オク下？","バーバヤーガ"]}]},
    {name:"syudou",directSongs:true,items:[{name:"syudou",songs:["邪魔","馬鹿","ビターチョコデコレーション","コールボーイ","コールガール","孤独の宗教","ジャックポットサッドガール","キュートなカノジョ +2"]}]},
    {name:"柊キライ",directSongs:true,items:[{name:"柊キライ",songs:["ギャラリア -4","ボッカデラベリタ","エバ"]}]},
    {name:"100回嘔吐",directSongs:true,items:[{name:"100回嘔吐",songs:["夏が終わっていきますね","最底辺の嫌がらせ"]}]},
    {name:"sasakure.UK",directSongs:true,items:[{name:"sasakure.UK",songs:["トンデモワンダーズ","スマートを模索する","阿呆なるものは","メイデー、メイビーネイビー"]}]},
    {name:"ねじ式P",directSongs:true,items:[{name:"ねじ式P",songs:["フリィダム ロリィタ","ピニャコラーダ","ice breaker","イカサマジュリエット","残酷と純粋","ノーブルローズ","パライソ・パライソ"]}]},
    {name:"wotaku",directSongs:true,items:[{name:"wotaku",songs:["DOGMA","シビュラ","ジェヘナ","snooze","マンハッタン"]}]},
    {name:"ナナホシ管弦楽団",directSongs:true,items:[{name:"ナナホシ管弦楽団",songs:["あのこどこのこ","失楽ペトリ","おねがいダーリン"]}]},
    {name:"真島ゆろ",directSongs:true,items:[{name:"真島ゆろ",songs:["チチンプイプイ"]}]}
  ]
};